version: '3.4'

services:
  store.productapi:
    image: ${DOCKER_REGISTRY-}storeproductapi
    build:
      context: .
      dockerfile: Store.ProductApi/Dockerfile
    ports:
      - "51000:50001"

  store.productapi-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "products", "-app-port", "80" ]
    depends_on:
      - store.productapi
    network_mode: "service:store.productapi"

  store.inventoryapi:
    image: ${DOCKER_REGISTRY-}storeinventoryapi
    build:
      context: .
      dockerfile: Store.InventoryApi/Dockerfile
    ports:
      - "52000:50001"

  store.inventoryapi-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "products", "-app-port", "80" ]
    depends_on:
      - store.inventoryapi
    network_mode: "service:store.inventoryapi"